### ISSUE TITLE
Not working now

### ISSUE THREAD

**Issue by crino85** [chrislennon/Crypto-Touchbar-App#95]
No Crypto available

**Comment by chrislennon** [comment]
Hey @crino85 - could you provide me more information - as to where you are not seeing any crypto displayed?

I have just checked the [webpage](https://chrislennon.github.io/Crypto-Touchbar-App/) and the scripts on BetterTouchTool and they seem to be working. I am testing on Chrome (version 80.0.3987.149) and BTT (version 3.182).

**Comment by Marubozu** [comment]
Hi Chris, yesterday evening, the script stopped working for me too. I gave it the night to see, and same thing. By checking the [webpage](https://chrislennon.github.io/Crypto-Touchbar-App/) you mention, I can see that all currencies are gone.
I am using:
- Chrome 81.0.4044.113 (Official Build) (64-bit)
- BTT 3.346
- MacOS 10.15.4

Not sure what happened. I am attaching 2 screenshots, let me know if I can provide anything else to help you 🙂 Thank you!

<img width="973" alt="Screenshot 2020-04-19 at 08 43 05" src="https://user-images.githubusercontent.com/36198887/79682497-c68b4d00-821a-11ea-9547-c61176602a1a.png">

<img width="1004" alt="Touch Bar Shot 2020-04-19 at 08 42 25" src="https://user-images.githubusercontent.com/36198887/79682498-c8eda700-821a-11ea-963f-8e9321cdf15f.png">

**Comment by chrislennon** [comment]
@Marubozu an interesting one! I'll focus on the web-app as its probably the same reason the touch bar is not working.
I am running the same mac and chrome versions as you and I get around 4600 coins returned.

Are there any errors in your [chrome developer console](https://developers.google.com/web/tools/chrome-devtools/open)? 

To get the list of coins I make a query to [Cryptocompare](https://status.cryptocompare.com/) - specifically this url https://min-api.cryptocompare.com/data/all/coinlist (here you should see a large JSON with all the coins) 

Is there anything in your browser or network that could be blocking this url/domain?

**Comment by Marubozu** [comment]
That should actually be the problem.

On the URL https://min-api.cryptocompare.com/data/all/coinlist I get the following message instead of the list of currencies (screenshot attached):

{"Response":"Error","Message":"You are over your rate limit please upgrade your account!","HasWarning":false,"Type":99,"RateLimit":{"calls_made":{"second":1,"minute":10,"hour":155,"day":713,"month":120792,"total_calls":923954},"max_calls":{"second":20,"minute":300,"hour":3000,"day":15000,"month":120000}},"Data":{}}

I'm not too much in development but I do understand there is an error 😃 And it looks like I eat too much data. What I am a bit surprised with is that I have been using the same script for the past 2 years or so.

I am displaying 8 cryptocurrencies on the TouchBar and I set it to refresh the rate every 60 seconds.

From what I understand form the error message is that it looks like the max amount of requests that can be made every month is 120,000. In my case, it means 8 per min x 60 x 24h x 30 d = 345,600 requests (considering the computer is always on, which is not the case).

As I am typing, I am trying to think what could trigger this after so long using the app. The only thing that comes to my mind is that I set the same TouchBar on my girlfriend's computer, who is using the same WiFi network. Not sure how CryptoCompare knows where requests are coming from. IP address? Script somewhere in BTT? Or Crypto Touchbar app? Because for setting it on my gf's computer, I simply exported all settings from my BTT app and imported them on her computer.

With my modest understanding of IT things, I tried to run a VPN and the rates are now back, which would suggest an IP check on CryptoCompare?

What is your opinion about this?

<img width="1349" alt="Screenshot 2020-04-19 at 11 39 02" src="https://user-images.githubusercontent.com/36198887/79685705-a23b6a80-8232-11ea-9db4-435c023bfcb6.png">

**Comment by chrislennon** [comment]
@Marubozu Thanks for that, that error is certainly more illuminating!

As you have already determined, you are hitting the public API limit - specifically the monthly quota.

I can think of few approaches:

1. Reduce the number/frequency of requests
  - number of coins, frequency of update etc
  - all requests (from your public IP - so including other machines on your network) using both BTT and my web-app will count towards your limit.
  - check no BTT scripts/presets still added or running on other machines that could be contributing to the number of calls
  - A VPN will change your IP and temporarily lift the restriction

2. I see that [Cryptocompare's pricing](https://min-api.cryptocompare.com/pricing) also has a free tier (with less requests than the public? 🤔) - this _may_ help
 - you could sign up to cryptocompare and on your [api page](https://www.cryptocompare.com/cryptopian/api-keys) you will get an API key.
- To use this you will need to modify the script inside BetterTouchTool
- Open the script and find the line that has the URL, it should look like this: `https://min-api.cryptocompare.com/data/pricemultifull?fsyms={}&tsyms={}`
- You should be able to add your API key onto the end of it like this `https://min-api.cryptocompare.com/data/pricemultifull?fsyms={}&tsyms={}&api_key=123-YOUR-API-KEY-HERE-456`

Option 1 will likely keep it alive more long term (though the monthly IP limit seems already reached). Option 2, may help - but I have some questions around their API rate limit, doesn't seem like many more requests are allowed than the public.

[Side note] - This tool is waaaaaay over due for an overhaul - if I go fixing things I will add a place in the web-app for users to more easily add their API key (assuming that turns out to me a more permanent fix)

**Comment by Marubozu** [comment]
Hi Chris, thanks so much for your help, I manage to solve the issue by following your advice! I hope this will help someone else too someday. Thanks also for making such great app!
